version: '3.7'

services:
  api: &willtheywinfastapi
    container_name: will_they_win_fast_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./src:/willtheywin-fast/src
      - ./tests:/willtheywin-fast/tests
      - ./migrations:/willtheywin-fast/migrations
      - ./willtheywinfastapi-dev.db:/willtheywin-fast/willtheywinfastapi-dev.db

    command: bash -c "uvicorn --host 0.0.0.0 --port 8000 --reload src.main:app"
    env_file:
      - ./dev.env
    environment:
      - DEBUG=1
#    depends_on:

volumes:
  willtheywinfastapi-dev.db:
